server:
  port: 8080  # 指定应用运行的端口号

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/truthPsy?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Lff@253116
    driver-class-name: com.mysql.cj.jdbc.Driver
  # HikariCP 连接池配置（默认）
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    max-lifetime: 600000
    connection-timeout: 30000

  # MyBatis 配置
  mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.example.demo.entity  # 你的实体类所在包
    configuration:
      map-underscore-to-camel-case: true  # 开启驼峰命名转换

# 日志配置（方便调试 SQL）
logging:
  level:
    com.example.demo.mapper: DEBUG  # 显示 MyBatis SQL 语句
